### ISSUE TITLE
simple example please?

### ISSUE THREAD

**Issue by klepsydra** [ccjr/alpaca-trade-api#3]
Forgive my ignorance, but after properly configuring the login, how can I do the simplest thing in **irb**?

For example, how do you Get open positions  "Client#positions" ? 

```

$ APCA_API_KEY_ID=P....C
$ APCA_API_SECRET_KEY=A...x
$ APCA_API_BASE_URL=https://api.alpaca.markets
$ irb
irb(main):001:0> require_relative 'helperlib'
=> true
irb(main):002:0> require 'alpaca/trade/api'
=> false
irb(main):003:0>  Alpaca::Trade::Client.positions()
Traceback (most recent call last):
        2: from /home/master/.rbenv/versions/2.5.6/bin/irb:11:in `<main>'
        1: from (irb):5
NameError (uninitialized constant Alpaca::Trade::Client)
irb(main):006:0> Alpaca::Trade::Client::positions()


Alpaca::Client.new()
Traceback (most recent call last):
        2: from /home/master/.rbenv/versions/2.5.6/bin/irb:11:in `<main>'
        1: from (irb):10
NameError (uninitialized constant Alpaca::Client)


```

Finally, I stumble into: 

```

 ac =  Alpaca::Trade::Api::Client.new

=> #<Alpaca::Trade::Api::Client:0x00005578f83a8d80 @data_endpoint="https://data.alpaca.markets", @endpoint="https://api.alpaca.markets", @key_id="P...A", @key_secret="5...Y">


irb(main):034:0> pp ac.positions()
[]
=> []




 ac.orders()
Traceback (most recent call last):
        8: from /home/master/.rbenv/versions/2.5.6/bin/irb:11:in `<main>'
        7: from (irb):32
        6: from /home/master/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/alpaca-trade-api-0.3.0/lib/alpaca/trade/api/client.rb:128:in `orders'
        5: from /home/master/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/alpaca-trade-api-0.3.0/lib/alpaca/trade/api/client.rb:128:in `map'
        4: from /home/master/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/alpaca-trade-api-0.3.0/lib/alpaca/trade/api/client.rb:128:in `each'
        3: from /home/master/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/alpaca-trade-api-0.3.0/lib/alpaca/trade/api/client.rb:128:in `block in orders'
        2: from /home/master/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/alpaca-trade-api-0.3.0/lib/alpaca/trade/api/client.rb:128:in `new'
        1: from /home/master/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/alpaca-trade-api-0.3.0/lib/alpaca/trade/api/order.rb:13:in `initialize'
TypeError (no implicit conversion of String into Integer)


```

# Yet I definitely do have positions, and orders.

**Comment by zakria03** [comment]
Worked for me with the following:

```
require 'alpaca/trade/api'

Alpaca::Trade::Api.configure do |config|
  config.endpoint = 'https://paper-api.alpaca.markets'
  config.key_id = 'xxxxxxxx'
  config.key_secret = 'xxxxx'
end

ac =  Alpaca::Trade::Api::Client.new
puts ac.orders().last.inspect
```

**Comment by ccjr** [comment]
Example added to README: https://github.com/ccjr/alpaca-trade-api#example
